<Project>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<DefineConstants>$(DefineConstants);NET9_0_OR_GREATER</DefineConstants>
	</PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);1591;NU1803;NU1608;NU1701</NoWarn>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTrimmable>False</IsTrimmable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<IncludeSymbols>True</IncludeSymbols>
	
		<Version>0.0.0</Version>
		<Authors>NineteenSevenFour</Authors>
		<Company>NineteenSevenFour</Company>
		<Copyright>NineteenSevenFour (2025)</Copyright>

		<RepositoryUrl>https://github.com/NineteenSevenFour/api.sdk</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<EnablePackageValidation>True</EnablePackageValidation>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageProjectUrl>https://github.com/NineteenSevenFour/api.sdk</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageIcon>nineteensevenfour_logo.png</PackageIcon>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<DelaySign>True</DelaySign>
		<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)nineteensevenfour-public.snk</AssemblyOriginatorKeyFile>
		<ApplicationIcon>$(MSBuildThisFileDirectory)NineteenFourSeven_logo.ico</ApplicationIcon>
		<SignAssembly>True</SignAssembly>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)nineteensevenfour_logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="$(MSBuildThisFileDirectory)LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="$(MSBuildThisFileDirectory)README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
