using AutoBogus;
using AutoBogus.Moq;

using NineteenSevenFour.Testing.Core.Extension;
using NineteenSevenFour.Testing.FluentBogus.Interface;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;

namespace NineteenSevenFour.Testing.FluentBogus
{
  public class FluentBogusBuilder<TFaker, TEntity> : FluentBogusBuilder<TEntity>, IFluentBogusBuilder<TFaker, TEntity>
      where TFaker : AutoFaker<TEntity>, new()
      where TEntity : class
  {
    /// <summary>
    /// Gets or sets the delegate used to configure the auto-generation of values using the specified configuration
    /// builder.
    /// </summary>
    /// <remarks>Assign a delegate to customize how values are generated by modifying the provided <see
    /// cref="IAutoGenerateConfigBuilder"/> instance. If not set, default configuration is used.</remarks>
    internal Action<IAutoGenerateConfigBuilder>? FakerConfigBuilder;

    /// <summary>
    /// Provides access to the AutoFaker instance used to generate fake data for the specified entity type.
    /// </summary>
    internal AutoFaker<TEntity>? Faker;

    /// <summary>
    /// Gets or sets the arguments used to configure the faker instance.
    /// </summary>
    internal object?[]? FakerArgs;

    /// <summary>
    /// The initial value used to seed random number generation or other deterministic processes.
    /// </summary>
    internal int Seed;

    /// <summary>
    /// Gets the list of property names to be skipped during processing.
    /// </summary>
    internal readonly List<string> SkipProperties = [];

    /// <summary>
    /// Contains the collection of rule set names associated with the current instance.
    /// </summary>
    internal readonly List<string> RuleSets = [];

    /// <summary>
    /// Gets a comma-separated string representation of all rule sets.
    /// </summary>
    internal string RuleSetString => string.Join(",", RuleSets);

    /// <summary>
    /// Stores the set of rules associated with their corresponding string keys.
    /// </summary>
    internal Dictionary<string, dynamic> RulesFor = [];

    /// <summary>
    /// Marks the specified property to be skipped during processing for the current entity type.
    /// </summary>
    /// <typeparam name="TProperty">The type of the property to be skipped.</typeparam>
    /// <param name="expr">An expression that identifies the property of the entity to skip. Must refer to a valid property or field of the
    /// entity type.</param>
    /// <exception cref="InvalidOperationException">Thrown if the specified property has already been marked to be skipped.</exception>
    internal void SkipInternal<TProperty>(Expression<Func<TEntity, TProperty>> expr)
    {
      var propertyOrFieldName = FluentExpression.MemberNameFor(expr);
      FluentExpression.EnsureMemberExists<TEntity>(propertyOrFieldName);

#pragma warning disable CS8604 // Possible null reference argument.
      if (!SkipProperties.Contains(propertyOrFieldName))
#pragma warning restore CS8604 // Possible null reference argument.
      {
        SkipProperties.Add(propertyOrFieldName);
      }
      else
      {
        throw new InvalidOperationException($"The property {propertyOrFieldName} for type {typeof(TEntity).Name} is already set to be skipped.");
      }
    }

    /// <summary>
    /// Adds the specified ruleset to the collection of active rulesets if it is not already present.
    /// </summary>
    /// <param name="ruleSets">The list of ruleset to add. Cannot be null, empty.</param>
    internal void UseRuleSetInternal(IEnumerable<string> ruleSets)
    {
      foreach (var ruleSet in ruleSets)
      {
        UseRuleSetInternal(ruleSet);
      }
    }

    /// <summary>
    /// Adds the specified ruleset to the collection of active rulesets if it is not already present.
    /// </summary>
    /// <param name="ruleset">The name of the ruleset to add. Cannot be null, empty, or consist only of white-space characters.</param>
    /// <exception cref="ArgumentOutOfRangeException">Thrown if the ruleset parameter is null, empty, or consists only of white-space characters.</exception>
    /// <exception cref="InvalidOperationException">Thrown if the specified ruleset has already been added.</exception>
    internal void UseRuleSetInternal(string ruleset)
    {
      // TODO: Validate RuleSet against TFaker
      if (string.IsNullOrWhiteSpace(ruleset))
      {
        throw new ArgumentOutOfRangeException(nameof(ruleset), $"A ruleset must be provided.");
      }

      if (!RuleSets.Contains(ruleset))
      {
        RuleSets.Add(ruleset);
      }
      else
      {
        throw new InvalidOperationException($"The ruleset {ruleset} is already set to be used.");
      }
    }

    /// <summary>
    /// Configures the specified builder with custom and default faker settings for entity generation.
    /// </summary>
    /// <remarks>This method applies user-defined faker configuration overrides, enforces the use of a
    /// specific binder, and configures properties to be skipped during entity generation. Intended for internal use
    /// within the entity generation pipeline.</remarks>
    /// <param name="builder">The builder used to configure auto-generation options for entities. Cannot be null.</param>
    internal void ConfigureFakerInternal(IAutoGenerateConfigBuilder builder)
    {
      // Call user define Faker configuration overrides
      FakerConfigBuilder?.Invoke(builder);

      // Force 
      builder.WithBinder<MoqBinder>();  // Configures the bind

      // Configures members to be skipped for a typeer to use
      foreach (var propName in SkipProperties)
      {
        builder.WithSkip<TEntity>(propName);
      }
    }

    /// <summary>
    /// Ensures that the internal faker instance is initialized for generating entity data.
    /// </summary>
    /// <exception cref="NullReferenceException">Thrown if the faker instance cannot be created, making data generation impossible.</exception>
    internal void EnsureFakerInternal()
    {
      Faker = (AutoFaker<TEntity>)Activator.CreateInstance(typeof(TFaker), FakerArgs)!;

      if (Faker == null) throw new NullReferenceException("The faker instance is not set. Generation of data is impossible.");
    }

    /// <summary>
    /// Initializes a new instance of the FluentBogusBuilder class by copying configuration from an existing builder and
    /// specifying a logger factory.
    /// </summary>
    /// <param name="fluentBogus">The existing FluentBogusBuilder instance from which to copy configuration settings. Cannot be null.</param>
    /// <param name="loggerFactory">The logger factory used to create loggers for this builder. Cannot be null.</param>
    internal FluentBogusBuilder(FluentBogusBuilder<TFaker, TEntity> fluentBogus, ILoggerFactory loggerFactory) : base(loggerFactory)
    {
      Seed = fluentBogus.Seed;
      FakerArgs = fluentBogus.FakerArgs;
      SkipProperties = fluentBogus.SkipProperties;
      RuleSets = fluentBogus.RuleSets;
      FakerConfigBuilder = fluentBogus.FakerConfigBuilder;
      RulesFor = fluentBogus.RulesFor;
    }

    /// <summary>
    /// Initializes a new instance of the FluentBogusBuilder class with the specified logger factory and optional
    /// arguments for the faker.
    /// </summary>
    /// <param name="loggerFactory">The logger factory used to create logger instances for this builder. Cannot be null.</param>
    /// <param name="args">An optional array of arguments to configure the faker. May be null or empty if no additional arguments are
    /// required.</param>
    public FluentBogusBuilder(ILoggerFactory loggerFactory, params object?[]? args) : base(loggerFactory)
    {
      FakerArgs = args;
    }

    /// <inheritdoc/>>
    public ICollection<TEntity> Generate(int count)
    {
      EnsureFakerInternal();
#pragma warning disable CS8602 // Dereference of a possibly null reference.
      return Faker
#pragma warning restore CS8602 // Dereference of a possibly null reference.
          .Configure((builder) => ConfigureFakerInternal(builder))
          .UseSeed(Seed)
          .Generate(count, RuleSetString);
    }

    /// <inheritdoc/>>
    public TEntity Generate()
    {
      EnsureFakerInternal();
#pragma warning disable CS8602 // Dereference of a possibly null reference.
      return Faker
#pragma warning restore CS8602 // Dereference of a possibly null reference.
          .Configure((builder) => ConfigureFakerInternal(builder))
          .UseSeed(Seed)
          .Generate(RuleSetString);
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> Skip(params Expression<Func<TEntity, object?>>[] properties)
    {
      if (properties?.All(expr => expr == null) ?? true)
      {
        throw new ArgumentOutOfRangeException(nameof(properties), $"A List of properties must be provided.");
      }

      foreach (var property in properties)
      {
        SkipInternal(property);
      }

      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> Skip<TProperty>(Expression<Func<TEntity, TProperty>> property)
    {
      SkipInternal(property);
      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> UseRuleSet(string ruleset)
    {
      UseRuleSetInternal(ruleset);
      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> UseRuleSet(params string[] rulesets)
    {
      if (rulesets?.All(string.IsNullOrWhiteSpace) ?? true)
      {
        throw new ArgumentOutOfRangeException(nameof(rulesets), $"A List of ruleset must be provided.");
      }

      UseRuleSetInternal(rulesets);

      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> UseSeed(int seed)
    {
      this.Seed = seed;
      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> UseArgs(object?[]? args)
    {
      this.FakerArgs = args;
      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> UseConfig(Action<IAutoGenerateConfigBuilder> configBuilder)
    {
      this.FakerConfigBuilder = configBuilder;
      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> RuleFor<TProperty, TPropEntity, TPropFaker>(
        Expression<Func<TEntity, TProperty>> property,
        IFluentBogusBuilder<TPropFaker, TPropEntity>? builder,
        int count)
        where TProperty : ICollection<TPropEntity?>?
        where TPropEntity : class
        where TPropFaker : AutoFaker<TPropEntity>, new()
    {
      var propOrFieldName = FluentExpression.MemberNameFor(property);
      FluentExpression.EnsureMemberExists<TEntity>(propOrFieldName);

      if (builder == null)
      {
        Skip(e => property);
      }
      else
      {
#pragma warning disable CS8604 // Possible null reference argument.
        RulesFor.Add(propOrFieldName, builder.Generate(count));
#pragma warning restore CS8604 // Possible null reference argument.
      }
      return this;
    }

    /// <inheritdoc/>>
    public IFluentBogusBuilder<TFaker, TEntity> RuleFor<TProperty, TPropFaker>(
        Expression<Func<TEntity, TProperty?>> property,
        IFluentBogusBuilder<TPropFaker, TProperty>? builder)
        where TProperty : class
        where TPropFaker : AutoFaker<TProperty>, new()
    {
      var propOrFieldName = FluentExpression.MemberNameFor(property);
      FluentExpression.EnsureMemberExists<TEntity>(propOrFieldName);

      if (builder == null)
      {
        Skip(e => property);
      }
      else
      {

#pragma warning disable CS8604 // Possible null reference argument.
        RulesFor.Add(propOrFieldName, builder.Generate());
#pragma warning restore CS8604 // Possible null reference argument.           
      }
      return this;
    }

  }
}
