<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>NineteenSevenFour.Testing.Example.Domain</Title>
    <PackageId>NineteenSevenFour.Testing.Example.Domain</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoBogus" Version="2.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NineteenSevenFour.Testing.FluentBogus.Relation\NineteenSevenFour.Testing.FluentBogus.Relation.csproj" />
  </ItemGroup>

</Project>
