name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
      - next
      - beta
      - alpha
      - '*.x' # maintenance releases branches
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: build-${{matrix.os}}-net${{matrix.dotnet}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [9.0.104] # dotnet format fails with newest versions if no parameter is passed

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Fetch full history
        shell: bash
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Setup git user to "NineteenSevenFour Bot"
        shell: bash
        run: |
          git config user.email "-" && \
          git config user.name "NineteenSevenFour Bot" && \
          git config --global init.defaultBranch main

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
          source-url: 'https://nuget.pkg.github.com/nineteensevenfour/index.json'
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install dependencies
        shell: bash
        run: dotnet restore ./nineteensevenfour.fluentbogus.sln
    
      - name: Run formating check
        shell: bash
        run: dotnet format

      - name: Build
        run: dotnet build --no-restore --configuration Release
        shell: bash
  
      - name: Run tests
        run: dotnet test --no-restore --configuration Debug --collect:"XPlat Code Coverage"  --results-directory:"./testresults/" "--settings" "./coverlet.runsettings"
        shell: bash
  
      - name: Report coverage (files)
        uses: codecov/codecov-action@v3
      
      - name: Report coverage (directory)
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          name: nineteensevenfour-fluentbogus-${{matrix.os}}-net${{matrix.dotnet}} # optional
          directory: './testresults/'
